#Webhook container
version: "3"
services:
  webhook:
    image: 192.168.50.5:5000/webhook:0.0.14
    container_name: webhook
    command: -verbose -hooks=/home/config/hooks.json -hotreload
    environment:
      - TZ=Europe/Brussels #optional
    volumes:
      - /mnt/user/WASP/webhook/:/home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: always
    env_file: .env
